### ISSUE TITLE
SSR working on some routes

### ISSUE THREAD

**Issue by ahaw** [EreckGordon/angular-universal-pwa-starter#3]
As in topic. When using home, chat or sign in/out site is not being rendered as universal page.
It seems it's working only for blog route.

**Comment by EreckGordon** [comment]
I'll dig into this issue this evening. I suspect the addition of websockets is messing with some server side rendering. I know that https://universal-demo.ereckgordon.com is rendering every page (right click view page source shows the rendering working), so something I have changed recently is likely the culprit.

Thanks for using this starter, hopefully I will solve this quickly.

**Comment by EreckGordon** [comment]
If you run a [lighthouse](https://developers.google.com/web/tools/lighthouse/) report on any page with a material button, you can see how it goes from unstyled to styled. This is because material currently has a bug where styles don't apply properly from universal server side rendering: https://github.com/angular/material2/issues/9865 so while that bug exists, it is very easy to see that the pages are rendering correctly.

you could also add 
```
        console.log(Object.keys(this.renderCache))
        Object.values(this.renderCache).forEach((value:string) => console.log(value.length))
```
right above this line: https://github.com/EreckGordon/angular-universal-pwa-starter/blob/master/server/modules/server-side-rendering/server-side-rendering.controller.ts#L10 and see the different values that are being cached.

I believe what you are seeing has to do with service worker caching. As soon as you have loaded the page once, the service worker takes over rather than hitting the server.  I'm currently messing with the different strategies, so my config file may change a bit over the next few days. I was told I was using the `dataGroups` category incorrectly, and at the time you posted this issue, `/blog` was in a dataGroups category that bypassed serving that chunk in the service worker.

**Comment by ahaw** [comment]
It seems your assumption about service worker is correct. When I disabled it SSR started working as expected.
